### ISSUE TITLE
Problem with compile.py - No module named internet.defer

### ISSUE THREAD

**Issue by hmmgit** [ggaughan/pipe2py#39]
I am using Python 2.7.8 on MacOSX 10.10.
I get this problem even if I run pip install -r requirements.txt.
 
``` 
$ python pipe2py/compile.py pipe1.json 
Traceback (most recent call last):
  File "pipe2py/compile.py", line 44, in <module>
    from pipe2py.modules.pipeforever import pipe_forever
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipe2py-0.23.0-py2.7.egg/pipe2py/modules/__init__.py", line 9, in <module>
    verbose = debug printing during compilation and running
ImportError: No module named internet.defer
```

**Comment by dskecse** [comment]
Same here. @ggaughan Could you please investigate the issue?

**Comment by ggaughan** [comment]
Please try an earlier version: https://github.com/ggaughan/pipe2py/issues/31#issuecomment-115795527
